<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostsTableSeeder extends Seeder
{
    public function run()
    {    
        DB::table('posts')->delete();
        DB::table('posts')->insert([
            [
                'id' => 8,
                'slug' => 'love-the-sentinel',
                'title' => 'Love the Sentinel',
                'description' => 'Jean-Honoré Fragonard frequently revisited the compositions featured in the pendant paintings...',
                'image_path' => '67dc6fc1189df-Love the Sentinel.jpg',
                'created_at' => '2025-03-20 19:42:57',
                'updated_at' => '2025-03-20 19:42:57',
                'user_id' => 1,
                'artist' => 'Jean Honoré Fragonard',
                'medium' => 'Oil on canvas',
                'origin' => 'France',
                'year' => 'c. 1773/1776',
            ],
            [
                'id' => 9,
                'slug' => 'madame-du-barry',
                'title' => 'Madame du Barry',
                'description' => 'Shown from the knees up, a woman stands facing and looking at us with her head tilted...',
                'image_path' => '67dc7bb524b23-Madame du Barry.jpg',
                'created_at' => '2025-03-20 20:33:57',
                'updated_at' => '2025-03-20 20:33:57',
                'user_id' => 1,
                'artist' => 'Élisabeth Louise Vigée Le Brun',
                'medium' => 'Oil on canvas',
                'origin' => 'France',
                'year' => '1782',
            ],
            [
                'id' => 10,
                'slug' => 'a-painter-s-studio',
                'title' => "A Painter's Studio",
                'description' => 'In a room filled with easels, white plaster heads and statuettes, a box of paints, books, and papers, a young woman stands looking at a sketch...',
                'image_path' => "67dc7c1a07f82-A Painter's Studio.jpg",
                'created_at' => '2025-03-20 20:35:38',
                'updated_at' => '2025-03-20 20:35:38',
                'user_id' => 1,
                'artist' => 'Louis-Léopold Boilly',
                'medium' => 'Oil on canvas',
                'origin' => 'France',
                'year' => 'c. 1800',
            ],
            [
                'id' => 11,
                'slug' => 'forest-interior-with-a-waterfall-papigno',
                'title' => 'Forest Interior with a Waterfall, Papigno',
                'description' => 'Gift of Mrs. John Jay Ide in memory of Mr. and Mrs. William Henry Donner.',
                'image_path' => '67dc7ca13fd01-Forest Interior with a Waterfall, Papigno.jpg',
                'created_at' => '2025-03-20 20:37:53',
                'updated_at' => '2025-03-20 20:37:53',
                'user_id' => 1,
                'artist' => 'André Giroux',
                'medium' => 'Oil on paper',
                'origin' => 'France',
                'year' => '1825/1830',
            ],
            [
                'id' => 12,
                'slug' => 'swiss-landscape',
                'title' => 'Swiss Landscape',
                'description' => 'We look out over a patchwork of cultivated fields that slope down to our right and back to an ice-blue lake...',
                'image_path' => '67dc7cfd57a60-Swiss Landscape.jpg',
                'created_at' => '2025-03-20 20:39:25',
                'updated_at' => '2025-03-20 20:39:25',
                'user_id' => 1,
                'artist' => 'Alexandre Calame',
                'medium' => 'Oil on paper on canvas',
                'origin' => 'Switzerland',
                'year' => 'c. 1830',
            ],
            [
                'id' => 13,
                'slug' => 'shakuntala',
                'title' => 'Shakuntala',
                'description' => "Raja Ravi Varma, a legend in Indian art, immortalized epic moments from ancient scriptures. \"Shakuntala\" is an enchanting story of love and desire, showcasing the delicate scene where Shakuntala, a key figure from the Mahabharata, feigns removing a thorn while covertly seeking her beloved, Dushyanta. Varma's careful focus on specifics and his combination of Indian and European methods bring the painting to life. The fusion of light, feelings, and elegance depicts a timeless romance on the canvas, resonating with future generations.",
                'image_path' => '67dc7e7c51f76-Shakuntala.jpg',
                'created_at' => '2025-03-20 20:45:48',
                'updated_at' => '2025-03-20 20:45:48',
                'user_id' => 2,
                'artist' => 'Raja Ravi Varma',
                'medium' => 'Oil on canvas',
                'origin' => 'India',
                'year' => 'c. 1870',
            ],
            [
                'id' => 14,
                'slug' => 'the-night-revels-of-han-xizai',
                'title' => 'The Night Revels of Han Xizai',
                'description' => "This painting is divided into five distinct sections and bears the seal of Shi Miyuan... (full description from SQL)",
                'image_path' => '67dc7f2c0701a-The Night Revels of Han Xizai.jpg',
                'created_at' => '2025-03-20 20:48:44',
                'updated_at' => '2025-03-20 20:48:44',
                'user_id' => 2,
                'artist' => 'Gu Hongzhong',
                'medium' => 'Ink and color on silk',
                'origin' => 'China',
                'year' => '10th-century',
            ],
            [
                'id' => 15,
                'slug' => 'equestrian-portrait-of-alexander-ii',
                'title' => 'Equestrian portrait of Alexander II',
                'description' => 'The Equestrian Portrait of Alexander II is a grand depiction of the Russian emperor... (full description from SQL)',
                'image_path' => '67dc802835688-Equestrian portrait of Alexander II.jpg',
                'created_at' => '2025-03-20 20:52:56',
                'updated_at' => '2025-03-20 20:52:56',
                'user_id' => 2,
                'artist' => 'Ilya Repin',
                'medium' => 'Oil on canvas',
                'origin' => 'Russia',
                'year' => '1913',
            ],
            [
                'id' => 16,
                'slug' => 'soap-bubbles',
                'title' => 'Soap Bubbles',
                'description' => 'A young man and child, both with pale skin, are framed within the rectangular opening of a stone window...',
                'image_path' => '67dc809cc5787-Soap Bubbles.jpg',
                'created_at' => '2025-03-20 20:54:52',
                'updated_at' => '2025-03-20 20:54:52',
                'user_id' => 2,
                'artist' => 'Jean Siméon Chardin',
                'medium' => 'Oil on canvas',
                'origin' => 'France',
                'year' => '1733/1734',
            ],
            [
                'id' => 19,
                'slug' => 'the-japanese-footbridge',
                'title' => 'The Japanese Footbridge',
                'description' => 'A pale turquoise footbridge arching over a pond lined with tall grasses...',
                'image_path' => '67df2835b5d22-The Japanese Footbridge.jpg',
                'created_at' => '2025-03-22 21:14:29',
                'updated_at' => '2025-03-22 21:17:09',
                'user_id' => 2,
                'artist' => 'Claude Monet',
                'medium' => 'Oil on Canvas',
                'origin' => 'France',
                'year' => '1899',
            ],
            [
                'id' => 20,
                'slug' => 'cosmos-convention',
                'title' => 'Cosmos Convention',
                'description' => 'This body of work was inspired by the garden planted by a free-spirited, beautiful young French chef...',
                'image_path' => '67df315bd9105-Cosmos Convention.png',
                'created_at' => '2025-03-22 21:53:31',
                'updated_at' => '2025-03-22 21:53:31',
                'user_id' => 1,
                'artist' => 'Carol Paquet',
                'medium' => 'Giclée Print',
                'origin' => 'Zambia',
                'year' => '2021',
            ],
            [
                'id' => 21,
                'slug' => 'cosmic-sight-iv',
                'title' => 'Cosmic Sight IV',
                'description' => 'This work is entirely formed by small motifs drawn in slow movements...',
                'image_path' => '67df324d279d3-Cosmic Sight IV.png',
                'created_at' => '2025-03-22 21:57:33',
                'updated_at' => '2025-03-22 21:57:33',
                'user_id' => 1,
                'artist' => 'Ghada Chamma',
                'medium' => 'Acrylic on canvas',
                'origin' => 'Tunisia',
                'year' => '2018',
            ],
            [
                'id' => 22,
                'slug' => 'for-me-to-live-is',
                'title' => 'FOR ME TO LIVE IS',
                'description' => 'I am Brave but I Bleed. I’m trying to answer the age-old question...',
                'image_path' => '67df32ebecfe2-FOR ME TO LIVE IS.png',
                'created_at' => '2025-03-22 22:00:11',
                'updated_at' => '2025-03-22 22:00:11',
                'user_id' => 1,
                'artist' => 'Leonie E Brown',
                'medium' => 'Acrylic on canvas',
                'origin' => 'South Africa',
                'year' => '2018',
            ],
            [
                'id' => 23,
                'slug' => 'derrame-espiritual',
                'title' => 'Derrame Espiritual',
                'description' => 'I was inspired by the depths of the earth, from the most intimate...',
                'image_path' => '67df337f05a4d-Derrame Espiritual.png',
                'created_at' => '2025-03-22 22:02:39',
                'updated_at' => '2025-03-22 22:12:34',
                'user_id' => 1,
                'artist' => 'Fernando Bosch',
                'medium' => 'Spraypaint',
                'origin' => 'Spain',
                'year' => '2020',
            ],
            [
                'id' => 24,
                'slug' => 'so-soft-and-so-lignt-2',
                'title' => 'so soft and so lignt',
                'description' => 'Oil on cradled canvas panel (mdf). A very textured painting...',
                'image_path' => '67df3412df457-so soft and so lignt.png',
                'created_at' => '2025-03-22 22:05:06',
                'updated_at' => '2025-03-22 22:18:43',
                'user_id' => 1,
                'artist' => 'Marta Grassi',
                'medium' => 'Oil on canvas panel',
                'origin' => 'France',
                'year' => '2021',
            ],
            [
                'id' => 25,
                'slug' => 'further',
                'title' => 'Further',
                'description' => 'Via alluvial systems and the liquid dynamics of paint...',
                'image_path' => '67df348058cce-Further.png',
                'created_at' => '2025-03-22 22:06:56',
                'updated_at' => '2025-03-22 22:06:56',
                'user_id' => 1,
                'artist' => 'Michael Denton',
                'medium' => 'Oil & acrylic',
                'origin' => 'United Kingdom',
                'year' => '2014',
            ],
            [
                'id' => 26,
                'slug' => 'flowers-from-mars',
                'title' => 'Flowers from Mars',
                'description' => 'This is acrylic and glitter painting on high quality linen...',
                'image_path' => '67df34ea7e403-Flowers from Mars.png',
                'created_at' => '2025-03-22 22:08:42',
                'updated_at' => '2025-03-22 22:08:42',
                'user_id' => 1,
                'artist' => 'Pamela Rys',
                'medium' => 'Acrylic and glitter on linen',
                'origin' => 'Poland',
                'year' => '2020',
            ],
            [
                'id' => 27,
                'slug' => 'girl-with-the-red-hat',
                'title' => 'Girl with the Red Hat',
                'description' => "Girl with the Red Hat is one of Johannes Vermeer's smallest works... (full description from SQL)",
                'image_path' => '67df366d4342b-Girl with the Red Hat.jpg',
                'created_at' => '2025-03-22 22:15:09',
                'updated_at' => '2025-03-22 22:15:09',
                'user_id' => 1,
                'artist' => 'Johannes Vermeer',
                'medium' => 'Oil on panel',
                'origin' => 'The Netherlands',
                'year' => 'c. 1669',
            ],
        ]);
    }
}